### ISSUE TITLE
proprietary & tracking libs in the app: could they be removed, please?

### ISSUE THREAD

**Issue by IzzySoft** [ya0211/MRepo#1]
This app sounds very promising! But is there a chance to do without proprietary libraries and trackers? A quick analysis of the latest release's APK brings up the following:

```
Offending libs:
---------------
* Crashlytics (/com/crashlytics): NonFreeDep,Tracking
* Firebase Data Transport (/com/google/android/datatransport): NonFreeNet
* Google Mobile Services (/com/google/android/gms): NonFreeDep
* Firebase (/com/google/firebase): NonFreeNet,NonFreeDep
* Firebase Analytics (/com/google/firebase/analytics): NonFreeDep,Tracking
* Firebase Installations (/com/google/firebase/installations): NonFreeNet

6 offenders.
```

I bet those are not needed for the app's functionality (and I wouldn#t wonder if removing Firebase Analytics and Crashlytics would make the other 4 disappear automatically). So would you consider a "pure FOSS build"? Thanks in advance!

**Comment by ya0211** [comment]
Thanks for the suggestion, actually the app's functionality doesn't need them. I'll remove all of them in the next commit.

**Comment by IzzySoft** [comment]
Cool, thanks a lot! Looking forward to the next release then, to add your app to [my repo](https://apt.izzysoft.de/fdroid) so it becomes easy to access for a broader audience :smiley:

**Comment by ya0211** [comment]
A new version has been released! 🥳

**Comment by IzzySoft** [comment]
That was fast – thanks! Checked, all looks fine, size was reduced quite a bit, too :smiley: So I've just added it to my repo (should [show up here](https://apt.izzysoft.de/fdroid/index/apk/com.sanmer.mrepo) in about 2.5h from now with the next sync) and will most certainly give it a try myself soon.

May I rise some questions which are not answered by the app description? Depending on your response they could be moved to separate issues then (as I consider this one here solved & completed now):

* will it be possible to add multiple repos to the app? Going by the screenshots (especially number 4) it seems like currently only a single repository is supported. I could e.g. imagine people wanting to add your repo, LSPosed repo and some more as well (I certainly would, to not need another app like FoxMM for the others)
* the app is intended to install modules with Magisk (not to maintain the backend that stores the modules), right?
* for maintaining the modules repo, code from [ya0211/magisk-modules-repo](https://github.com/ya0211/magisk-modules-repo) can be used. There, `sync.py` takes care to pull in the files specified in the JSON. Does it also take care to add new versions of modules defined in the JSON, or is that a task to be done manually? If I interpret this correctly going by the 3 examples given (please correct me if I'm wrong): "Upload from updateJson" would automatically fetch the latest version (with the update URL maintained by the corresponding dev), while in the other 2 cases it would be the responsibility of the "repo maintainer" to adjust the `update` URL so `sync.py` fetches the latest files?
* after running `sync.py`, `git add|commit|push` need to be performed separately?
* are forges other than Github (GitLab, Gitea etc.) supported by the app as well?

With the questions answered I'd update the app description a bit I guess. I then gladly provide the results here as PR if you like, using [Fastlane structures](https://gitlab.com/-/snippets/1895688) to give back control over how your app is presented to you. I might also try setting up my own modules repo and provide the notes on "getting started" for the other repo :wink:

**Comment by ya0211** [comment]
### Questions

- Support for adding multiple repo, I'm sure this will be the focus of next version.
- MRepo is intended to install modules with Magisk
- Currently `repo` is actually just a JSON with all the information about the module. So `repo` are free, just give a compliant JSON. I'm not sure if this is the best way, but it should be the easiest for the user.
- The current version also supports defining a URL pointing to JSON as a warehouse. I am not sure whether GitHub (Gitlab, Gittea, etc.) is particularly supported, and their APIs should be different (I don't know much about it). I think a JSON with all the information is a good choice.
- If you have any other questions or I haven't made it clear, I've been here.

### Other

- MRepo is just getting started, and I'm just a beginner in Android app development, I believe there is still a lot of work to be done. Finally, thank you for liking MRepo and adding it to f-droid. I will try to make it better.
- Please feel free to contribute by asking for Issues or PR🥳

**Comment by ya0211** [comment]
> * how can I include the license used by the resp. module? `sync.py` overwrites the description with details from `module.prop`, and I found no dedicated field.

You mean the module's own license?

**Comment by IzzySoft** [comment]
> You mean the module's own license?

Exactly. It's not part of the `module.prop`, so it cannot be obtained from there. And while Github/GitLab APIs have a way to obtain the [SPDX](https://spdx.org/licenses/) name, that would make things more complicated. I've come up with a quick hack, adding a `license` field to the JSON and adjusting `sync.py` slightly (as I don't know if the format is standard, or the app would understand the new field directly):

```python
    @staticmethod
    def update_info(item: dict, file: Path):
        prop = get_props(file).dict
        item["name"] = prop["name"]
        item["version"] = prop["version"]
        item["versionCode"] = prop["versionCode"]
        item["author"] = prop["author"]
        if "license" in item:
            item["description"] = "{0} License: {1}".format(prop["description"], item["license"])
        else:
            item["description"] = prop["description"]
```

Example result (with a dummy repo not yet established, and `sync.push()` commented out:

```json
    {
      "id": "uperf",
      "update": "https://github.com/yc9559/uperf/raw/master/version.json",
      "name": "Uperf",
      "version": "v3(22.09.04)",
      "versionCode": "220904",
      "license": "Apache-2.0",
      "author": "Matt Yang",
      "description": "Userspace performance controller for android. Repo: https://github.com/yc9559/uperf/ License: Apache-2.0",
      "states": {
        "zipUrl": "https://raw.githubusercontent.com/IzzySoft/magisk-modules-repo/master/modules/uperf/v3(22.09.04).zip",
        "changelog": "https://github.com/yc9559/uperf/raw/master/changelog.md"
      }
```

Feel free to use that (or have the "license" field understood directly). For me the license is important as my repo would only accept F/LOSS modules.

> MRepo is intended to install modules with Magisk

Thanks! Description updated accordingly (will be propagated with the next sync in 24h). Shall I open a new issue for multi-repo support then?

> is actually just a JSON with all the information about the module

Totally fine with me – I'd most likely approached it the very same way. A definition of fields used could be part of the description there (e.g. in the Readme), but that's easily reverse-engineered (unless there are some rare optional fields). If the code (especially the `util` directory) would be available in a repository separate from the modules, that would make participation/contribution easier: I currently just copied the files as I didn't want to fork/clone the entire repository with all the modules inside :see_no_evil:

> I am not sure whether GitHub (Gitlab, Gittea, etc.) is particularly supported, and their APIs should be different

Yes, their APIs are indeed different (I know that as I'm using them with my F-Droid repo). But seeing `sync.py` does use pure git commands, the forge should make no difference there. The client (this app here) probably just pulls the `modules.json`, reads it, and the only other "contact" would be using the `zipUrl` to obtain the module itself if the user wants to install it. So if I wanted to use Gitea to host my repo:

```python
GITHUB_RAW_URL = "https://codeberg.org"
MODULE_REPO = "izzy/magisk-modules-repo"
REPO_BRANCH = "master"
REPO_URL = "{0}/{1}/raw/branch/{2}".format(GITHUB_RAW_URL, MODULE_REPO, REPO_BRANCH)
```

should work. Note that for Github a similar syntax would work as well: `https://github.com/ya0211/magisk-modules-repo/raw/main/README.md` would redirect properly. But never mind that; the maintainer of the repo can set up those variables easily (though that should be done in a config file, not in the code directly), and the app should then be able to use the resulting URL. For GitLab, the syntax would be close to that as well: simply replace the `blob` you get when visiting with a browser by `raw` :wink:

Finally, thanks for your swift responses! I'll then prepare a PR with Fastlane ASAP, as indicated. I'll also start playing with my own repo (probably using Forgejo at Codeberg.org which is my "main base" for hosting repos) and might then open issues/PRs at the other repo with my "findings".

> Finally, thank you for liking MRepo and adding it to f-droid

Oh, gladly done (and it's [live now in my repo](https://apt.izzysoft.de/fdroid/index/apk/com.sanmer.mrepo), but not yet at F-Droid.org – if you want it listed there I can help you with that as well, being one of the F-Droid maintainers). For now, be welcome to [pick a badge](https://gitlab.com/IzzyOnDroid/repo/#if-my-app-is-available-here-do-you-have-a-badge-i-can-use-to-link-to-it) to link to your app's presence in my repo :smiley:

I was already looking to set up my own Magisk repo but had not yet figured how to do that, and how to get such a repo available in a way that makes it easy to use for the "average Jane & Joe". Your app and scripts seem to make that possible, so I'll see to it this year I guess. Once your app supports multiple repos, I'll have to speed up things to get that running :see_no_evil:

**Comment by ya0211** [comment]
### Repo
- Add license field in JSON(how to get it)
- `Repo` and `sync.py` will be separated
- Variables of `Repo` will be done in a config file (a common template config)

### App
- Support multiple repos

### Other
I mean f-droid is not f-droid.org, my understanding is that IzzyOnDroid is also f-droid isn't it?

**Comment by ya0211** [comment]
### Repo
- Add license field in JSON(how to get it)
- `Repo` and `sync.py` will be separated
- Variables of `Repo` will be done in a config file (a common template config)

### App
- Support multiple repos

### Other
I mean f-droid is not f-droid.org, my understanding is that IzzyOnDroid is also f-droid isn't it?

**Comment by IzzySoft** [comment]
> I mean f-droid is not f-droid.org, my understanding is that IzzyOnDroid is also f-droid isn't it?

Ambiguity, yeah…

* F-Droid.org: the organisation
* F-Droid.org: the domain
* F-Droid.org: the website
* F-Droid: the team
* F-Droid: the repo of apps
* F-Droid: the software maintaining the repo
* IzzyOnDroid: using that software (aka "r3d party repo")
* IzzyOnDroid: me as a person, running this 3rd party repo while also being member of the F-Droid team and one of the maintainers there
* [IzzyOnDroid](https://android.izzysoft.de/): the website with app listings, articles and more
* …

> Repo and `sync.py` will be separated

Thanks! I see that already happened, so I'll now fork and clone [magisk-modules-repo-util](https://github.com/ya0211/magisk-modules-repo-util) (done)

> * Add license field in JSON(how to get it)
> * Variables of Repo will be done in a config file (a common template config)

Shall I open issues for that over where they belong? You might also wish to move my other 2 issues over there (not sure if Github allows that – I just know it's possible at GitLab).

> Support multiple repos

Looking forward to that, thanks!

**Comment by ya0211** [comment]
There will be new issues [#1](https://github.com/ya0211/magisk-modules-repo-util/issues/1#issue-1523722567) opened in [magisk-modules-repo-util](https://github.com/ya0211/magisk-modules-repo-util) about the repo, the discussion here will not continue.

**Comment by IzzySoft** [comment]
Thanks! Subscribed there.

**Comment by IzzySoft** [comment]
Btw, as 2 of your apps are now in my repo: would you like to [pick a badge](https://gitlab.com/IzzyOnDroid/repo/#if-my-app-is-available-here-do-you-have-a-badge-i-can-use-to-link-to-it) to link there from your respective Readmes, @ya0211? There's even one that would fit fine next to your download counter, telling which version is live in my repo :wink:
