### ISSUE TITLE
[FR] Search module descriptions as well as titles

### ISSUE THREAD

**Issue by GreenDotBlue99** [ya0211/MRepo#101]
### Checklist / 检查清单

- [X] No one has submitted a similar or identical feature request before. / 之前没有人提交过类似或相同的功能请求。
- [X] This suggestion does not depart from the original intention of MRepo. / 这个建议不会背离 MRepo 的初衷。

### Enhancement propose / 改进目的

Currently repo module Search searches only titles bringing little results. 

### Solution / 解决方案

Add search module descriptions as well.

**Comment by ya0211** [comment]
Added in https://github.com/ya0211/MRepo/commit/addd251022c0e6d7c228bc6f27987ba14e0e858d

**Comment by GreenDotBlue99** [comment]
Check how versatile the search is on LSposed module repo :)
