### ISSUE TITLE
[BUG] Unable to access ViewModel after the NavBackStackEntry is destroyed

### ISSUE THREAD

**Issue by Wjxfi** [ya0211/MRepo#11]
#7. the bug has not been fixed. The latest version of the application is installed.

**Comment by ya0211** [comment]
please send log

**Comment by ya0211** [comment]
The full log file, only this I can't tell what's causing it.

`shortcut -> log -> share`, this will export the app log file, the crash of the app will not affect the start of the log activity.

**Comment by ya0211** [comment]
You are using root mode, please switch to non-root mode

**Comment by ya0211** [comment]
I can't confirm what caused the ViewModel to be cleaned (maybe MIUI, but I didn't get similar reports on other devices), I suggest you uninstall and reinstall the app (I'm not sure this will help).

**Comment by ya0211** [comment]
Sorry to tell you, this seems to come from the integration of androidx navigation and lifecycle, but I only found it on MIUI so far, I will continue to pay attention to this issue.

**Comment by ya0211** [comment]
It is a bug with the navigation-animation. There is no way to fix it in App, but I will try to make navigation-animation optional.
