### ISSUE TITLE
[Feature Request] Magisk Modules Alternative Repository

### ISSUE THREAD

**Issue by Heus-Sueh** [ya0211/MRepo#13]
could you add this [repository](https://github.com/Magisk-Modules-Alt-Repo)? then you can leave it disabled by default and leave a warning for users: "**I do not have any responsibility if the modules of this repository cause brick or bootloop**"

**Comment by ya0211** [comment]
https://github.com/ya0211/magisk-modules-alt-repo

**Comment by wefalltomorrow** [comment]
> https://github.com/ya0211/magisk-modules-alt-repo

Will this get updated?

**Comment by ya0211** [comment]
Yeah, but i don't have time to do it now.
