### ISSUE TITLE
Add Spanish language

### ISSUE THREAD

**Issue by JesusMaxim** [ya0211/MRepo#14]
How could I contribute to the translation of this language?

**Comment by ya0211** [comment]
Sorry, this isn't ready yet. I'll make this available on Crowdin before the next release, you can wait for me to finish it. If you know the resource layout of the Android app, you can also provide the translation as a PR.

**Comment by JesusMaxim** [comment]
Yes, please

**Comment by ya0211** [comment]
> Yes, please

Because registration is not open now, please send me **your email** and I will send you an invitation (via [telegram](https://t.me/sanmer), [twitter](https://twitter.com/ya021112) or here).
