### ISSUE TITLE
How to sort the cloud modules?

### ISSUE THREAD

**Issue by ovizii** [ya0211/MRepo#27]
It looks like they are sorted by name, am I missing something or is there no way to sort by say last updated?

**Comment by ya0211** [comment]
Duplicate of #22

**Comment by ovizii** [comment]
Sorry about that, I searched your issues for the word "sort" and didn't find the linked issue since it only talks about filtering 😅

**Comment by ya0211** [comment]
That's ok, thanks for your interest in MRepo.
