### ISSUE TITLE
[FR] 

### ISSUE THREAD

**Issue by RichardBeisser** [ya0211/MRepo#29]
### Checklist / 检查清单

- [X] No one has submitted a similar or identical feature request before. / 之前没有人提交过类似或相同的功能请求。
- [X] This suggestion does not depart from the original intention of MRepo. / 这个建议不会背离 MRepo 的初衷。

### Enhancement propose / 改进目的

Hello,

please be so kindly and compile also an arm-v7a version of the App.

Older samsung devices have a 32bit Version of Android.
For example user retiredtab at XDA releases monthly android 11/12 CustomRoms for many older Samsung devices, f.ex. for SM-T550
It's not possible to create a 64bit Custom Rom because everything (like drivers) which has to be taken from samsung is 32bit and closed source.

Big Thanks

**Comment by ya0211** [comment]
There is no native library in the alpha version or ci versions.

**Comment by RichardBeisser** [comment]
> There is no native library in the alpha version or ci versions.

???
could you please explain this?

**Comment by ya0211** [comment]
@RichardBeisser 
The `c/c++` code has been removed, so there is no need to compile for different CPU architectures.

You can use the ci version, because next version will not be released yet. But the latest released version of MRepo has compiled 32-bit🤔.

**Comment by RichardBeisser** [comment]
oh, it was a mistake of me.
I had no look here at github, only at f-droid.
you alread have compiled a arm-v7a version
