### ISSUE TITLE
[FR] Donation link request

### ISSUE THREAD

**Issue by ghost** [ya0211/MRepo#30]
### Checklist / 检查清单

- [X] No one has submitted a similar or identical feature request before. / 之前没有人提交过类似或相同的功能请求。
- [X] This suggestion does not depart from the original intention of MRepo. / 这个建议不会背离 MRepo 的初衷。

### Enhancement propose / 改进目的

I want to keep this project alive, "AMM" can go straight in to the trash bin.

Paypal/BTC/Monero

Also, could you make a telegram channel for users to chat in?

Regards
Someone who dislikes Androidancy

**Comment by ya0211** [comment]
BTC: bc1q5nnke896rwqnsfxhl5syx4pvykmjke40n2wg2t
ETH: 0x9605Ee5f6C6b7013383F4f3BE4Cbc03c5950af28

Telegram: https://t.me/mrepo_group
