### ISSUE TITLE
Latest version not useful at all

### ISSUE THREAD

**Issue by HarriBuh** [ya0211/MRepo#31]
Version 1.5.0

AFAIK, the earlier versions of this app would at least provide a larger variety of apps inside the Sanmer repo.

The current version, though, has almost no repos left to download. Ten, to be precise .It does not provide any information about the apps. It's just a shell of an app.
I do respect the fact that it's still in a very early stage of development, but it's completely useless for me atm.
This frustrates me because I hate the reworked Fox2Code Magisk Module App by Androidacy, as it's full of ads, trackers and just too bloated in general.

What's next on your schedule?

**Comment by ya0211** [comment]
- If you think MRepo is useless, you can choose other ones you like.
- If you need a repository with more modules, you can collect your favorite modules and build a repo for MRepo by [util](https://github.com/ya0211/magisk-modules-repo-util).
