### ISSUE TITLE
[FR] In-app update feature

### ISSUE THREAD

**Issue by symbuzzer** [ya0211/MRepo#32]
### Checklist / 检查清单

- [X] No one has submitted a similar or identical feature request before. / 之前没有人提交过类似或相同的功能请求。
- [X] This suggestion does not depart from the original intention of MRepo. / 这个建议不会背离 MRepo 的初衷。

### Enhancement propose / 改进目的

As written in title, need simple mechanism for checking update for app

**Comment by ya0211** [comment]
No plan, MRepo updates will not be very frequent.
