### ISSUE TITLE
Refactor MRepo

### ISSUE THREAD

**Issue by ya0211** [ya0211/MRepo#4]
### Features
- [x] Show the historical version of the module
- [x] Support multiple repos

### UI
- [x] A new designed `ui/page/home`
- [x] A new designed `ui/page/modules`
- [x] Add new page `ui/page/viewmodule`
- [x] Add new page `ui/page/repository`

###  Compatibility with established repos
- Use [magisk-modules-repo-util](https://github.com/ya0211/magisk-modules-repo-util) to convert repos into json available to MRepo
- Currently only GitHub is supported, such as [Magisk-Modules-Repo](https://github.com/Magisk-Modules-Repo), [Magisk-Modules-Alt-Repo](https://github.com/Magisk-Modules-Alt-Repo)

**Comment by IzzySoft** [comment]
"Compatibility with established repos" is striked-through – does that mean it's already done, or does the included word "(future)" mean this will be part of a separate issue?

**Comment by ya0211** [comment]
> "Compatibility with established repos" is striked-through – does that mean it's already done, or does the included word "(future)" mean this will be part of a separate issue?

I'm not sure when it will be implemented, will or will not wait until the current work is done before considering it.

**Comment by IzzySoft** [comment]
K, tnx. As long as the magisk-modules-repo-util part covers both there's no rush with it here I guess.

**Comment by Coding-Sn4ke** [comment]
It keeps on crashing.

**Comment by ya0211** [comment]
> It keeps on crashing.
I need logs, and information about your device.
