### ISSUE TITLE
Refactor Modules/Cloud & View Module

### ISSUE THREAD

**Issue by zgfg** [ya0211/MRepo#5]
For many modules, clicking to Changelog displays then readme.md instead of the changelog.md

For one module I even got 404 Not found for the Changelog

**Comment by zgfg** [comment]
![IMG_20230221_215608](https://user-images.githubusercontent.com/51943147/220464448-55a70668-2ced-4bd3-9081-7f414fe8319c.jpg)

![IMG_20230221_215635](https://user-images.githubusercontent.com/51943147/220464496-802de3d5-da97-410d-9496-0bba4e555f69.jpg)

**Comment by ya0211** [comment]
> For many modules, clicking to Changelog displays then readme.md instead of the changelog.md
> 
> For one module I even got 404 Not found for the Changelog

changlog.md is originally for modules that provide updateJson, I will add README .mdfor modules that do not have updateJson.

CrazyBytesVE's module gets a 404 because he uses \r for newlines instead of \n in the text editor he's using, which affects URL generation.

**Comment by zgfg** [comment]
![camera1](https://user-images.githubusercontent.com/51943147/220561281-c1ca2e0e-567a-4f36-92cb-6c486800d20f.jpg)
![camera2](https://user-images.githubusercontent.com/51943147/220561325-ac43f229-bb5b-45b3-b49b-c06bd6a94c7b.jpg)

**Comment by zgfg** [comment]
The same module also provides LICENSE file but when I click to the GPL-2.0 license in MRepo it opens again README.md
![camera3](https://user-images.githubusercontent.com/51943147/220561735-a8eca46d-47c5-4cc2-8f5a-ebdcf0f44c36.jpg)

**Comment by zgfg** [comment]
Similarly for my ToyBox-Ext, there is no option to click for Changeling in MRepo but Magisk app and eg Fox MMM correctly display the changelog.md (my repo also provides changelog.md and updateJson
![toybox1](https://user-images.githubusercontent.com/51943147/220562384-4145b1dc-0cce-40c3-b3f1-54e0329ca8a0.jpg)
![toybox2](https://user-images.githubusercontent.com/51943147/220562433-447bd12d-0e74-435a-8ed9-1975ef6215c9.jpg)
![toybox3](https://user-images.githubusercontent.com/51943147/220562461-17a65b50-a378-4529-adb3-1174e5c7bbe2.jpg)

Similarly, I have LICENSE file but clicking to OBSD license in MRepo opens again README.md

**Comment by zgfg** [comment]
Similarly, I have LICENSE file but clicking to OBSD license in MRepo opens again README.md
![toybox4](https://user-images.githubusercontent.com/51943147/220563586-b6069bdb-7c47-44e9-b933-a6ff675da00b.jpg)

**Comment by ya0211** [comment]
I just refactored the util, and the sync for Magisk-Modules-Alt-Repo (and similar repo) is still being optimized.

Thanks for your suggestion, I will add the judgment of update.json, if it exists, it will be used first, then changlog.md, and finally readme.md.

For the display of the license, the chip displayed under modules/cloud is not clickable, because the card has a click event, and I will not add it to the content. Currently, I'm not planning to add a display license to the chip inside the view module.

**Comment by zgfg** [comment]
Please test yourself - these chips are clickable but they open README.md
![camera3](https://user-images.githubusercontent.com/51943147/220568618-03e232aa-81fc-4d3c-a580-98b519fb132c.jpg)
![toybox4](https://user-images.githubusercontent.com/51943147/220568660-8c6710b2-4237-45a2-b164-7afc6198881e.jpg)

This is when you scroll or search through all modules on Cloud (not when you already 'open' one of them - at that later time, when you already 'open' one module, then license is no more clickable)

**Comment by ya0211** [comment]
> Please test yourself - these chips are clickable but they open README.md ![camera3](https://user-images.githubusercontent.com/51943147/220568618-03e232aa-81fc-4d3c-a580-98b519fb132c.jpg) ![toybox4](https://user-images.githubusercontent.com/51943147/220568660-8c6710b2-4237-45a2-b164-7afc6198881e.jpg)
> 
> This is when you scroll or search through all modules on Cloud (not when you already 'open' one of them - at that later time, when you already 'open' one module, then license is no more clickable)

These chips are custom components, this component does not define a click event, so clicking them will only trigger the click event of the parent component

**Comment by zgfg** [comment]
Video for clicking on the license is here:
https://mega.nz/file/Nt1gyYjY#ofUKEFtlmbyq8sQI3DN0GS-HM_TIekYok4L_D3ETMJ4

**Comment by ya0211** [comment]
> Video for clicking to the license is here:
> https://mega.nz/file/Nt1gyYjY#ofUKEFtlmbyq8sQI3DN0GS-HM_TIekYok4L_D3ETMJ4

No other click events will be added to the modules/cloud cards, the purpose of these chips is just to make the information more obvious. I would consider adding a click event to the license chip in the view module to navigate to the license text.

**Comment by zgfg** [comment]
> > Please test yourself - these chips are clickable but they open README.md ![camera3](https://user-images.githubusercontent.com/51943147/220568618-03e232aa-81fc-4d3c-a580-98b519fb132c.jpg) ![toybox4](https://user-images.githubusercontent.com/51943147/220568660-8c6710b2-4237-45a2-b164-7afc6198881e.jpg)
> > This is when you scroll or search through all modules on Cloud (not when you already 'open' one of them - at that later time, when you already 'open' one module, then license is no more clickable)
> 
> These chips are custom components, this component does not define a click event, so clicking them will only trigger the click event of the parent component

Maybe just disable the clicks on them to avoid misunderstanding

---

Btw, I tested Install and Update for couple of modules from MRepo and it worked fine

Maybe you could provide Install/Update but also Download - like in the Magisk 

Sometimes one wants to download and inspect the module zip installation file, without already installing that module

![toybox5](https://user-images.githubusercontent.com/51943147/220573811-a33175fd-88b5-4d52-b5c6-5c0745add1b5.jpg)

**Comment by ya0211** [comment]
OK, the click of the chip under modules/cloud will be disabled.  
Items inside versions are clickable, and they have such a dialog.
There is an install button in the view module so that users can directly install the latest version, I would modify it to opening a dialog like item in versions.

**Comment by zgfg** [comment]
👍

**Comment by ya0211** [comment]
### Status

- no add README.md. if the developer configures the changlog in updateJson as READM.md, not be adapted separately
- If the configuration error of changlog causes MRepo to crash when view changlog, such as [NavBar_Resize_MIUI](https://github.com/Magisk-Modules-Alt-Repo/NavBar_Resize_MIUI), [NavBar_Resize_AOSP](https://github.com/Magisk-Modules-Alt-Repo/NavBar_Resize_AOSP), not be adapted separately
