### ISSUE TITLE
Still issues with Changelog (crash or half-visible)

### ISSUE THREAD

**Issue by zgfg** [ya0211/MRepo#6]
For the two modules from Alt Repo, MRepo crashes when I click on Changelog
![Screenshot_2023-02-24-15-34-34-367_com sanmer mrepo-edit](https://user-images.githubusercontent.com/51943147/221204917-48754526-80e3-4604-94a4-b262410f3da9.jpg)
![Screenshot_2023-02-24-15-27-32-618_com miui home-edit](https://user-images.githubusercontent.com/51943147/221204996-4da60870-a2b4-4a5e-9a48-b38353093eb9.jpg)

**Comment by zgfg** [comment]
For the others it opens the Changelog but half of the box is not visible: #
![Screenshot_2023-02-24-15-30-27-315_com sanmer mrepo](https://user-images.githubusercontent.com/51943147/221205771-0802cf58-1915-4d15-9277-d4906fb46632.jpg)

**Comment by zgfg** [comment]
Btw, I had removed Alt Repo from the Settings and re-added and it was now automatically refreshed

Also, the Licenses are now correctly displayed - thanks:
![Screenshot_2023-02-24-15-31-06-622_com sanmer mrepo](https://user-images.githubusercontent.com/51943147/221206279-5a4d83eb-03ba-48cd-a200-eff07450d9c7.jpg)

**Comment by ya0211** [comment]
> For the two modules from Alt Repo, MRepo crashes when I click on Changelog ![Screenshot_2023-02-24-15-34-34-367_com sanmer mrepo-edit](https://user-images.githubusercontent.com/51943147/221204917-48754526-80e3-4604-94a4-b262410f3da9.jpg) ![Screenshot_2023-02-24-15-27-32-618_com miui home-edit](https://user-images.githubusercontent.com/51943147/221204996-4da60870-a2b4-4a5e-9a48-b38353093eb9.jpg)

The Changelog of these two modules points to a web page instead of a text, which I think is the developer's responsibility.

**Comment by ya0211** [comment]
> For the others it opens the Changelog but half of the box is not visible: ![Screenshot_2023-02-24-15-30-27-315_com sanmer mrepo](https://user-images.githubusercontent.com/51943147/221205771-0802cf58-1915-4d15-9277-d4906fb46632.jpg)

May be caused by [Update dependencies](https://github.com/ya0211/MRepo/commit/f41d5c613b0fe98b04584d4e0fa044418b33989d), I'm testing

**Comment by zgfg** [comment]
> > For the two modules from Alt Repo, MRepo crashes when I click on Changelog ![Screenshot_2023-02-24-15-34-34-367_com sanmer mrepo-edit](https://user-images.githubusercontent.com/51943147/221204917-48754526-80e3-4604-94a4-b262410f3da9.jpg) ![Screenshot_2023-02-24-15-27-32-618_com miui home-edit](https://user-images.githubusercontent.com/51943147/221204996-4da60870-a2b4-4a5e-9a48-b38353093eb9.jpg)
> 
> The Changelog of these two modules points to a web page instead of a text, which I think is the developer's responsibility.

Just checked the changeling.md for NavBar MIUI , and it looks as a proper MD file:
https://github.com/Magisk-Modules-Alt-Repo/NavBar_Resize_MIUI/raw/main/changelog.md

Also for NavBar AOSP module:
https://github.com/Magisk-Modules-Alt-Repo/NavBar_Resize_AOSP/raw/main/changelog.md

**Comment by ya0211** [comment]
The release has been updated, if the changelog shows that there is a problem (not the app crashes), please reinstall [MRepo](https://github.com/ya0211/MRepo/releases/tag/v1.1.1).
