### ISSUE TITLE
[FR] Support for Official magisk json format

### ISSUE THREAD

**Issue by mrovx** [ya0211/MRepo#67]
### Checklist / 检查清单

- [X] No one has submitted a similar or identical feature request before. / 之前没有人提交过类似或相同的功能请求。
- [X] This suggestion does not depart from the original intention of MRepo. / 这个建议不会背离 MRepo 的初衷。

### Enhancement propose / 改进目的

I found this repo which has json for official magisk modules repository. but it seem that Mrepo uses different json. 

### Solution / 解决方案

its either support official magisk format or convert them to mrepo format?

### Additional info / 额外信息

although the official repo does not open new submissions, but this is more trusted

**Comment by mrovx** [comment]
wait, i think i wrong about official repo format

**Comment by ya0211** [comment]
- I don't have a plan for that. 
- You can try building a mirror by [util](https://github.com/ya0211/magisk-modules-repo-util), refer to [ya0211/magisk-modules-alt-repo](https://github.com/ya0211/magisk-modules-alt-repo).
