### ISSUE TITLE
[BUG]  Does not use configured proxy

### ISSUE THREAD

**Issue by eku** [ya0211/MRepo#78]
### Checklist / 检查清单

- [X] No one has submitted a similar or identical bug report before. / 之前没有人提交过类似或相同的 bug report。
- [X] I'm using the latest version of MRepo. / 我正在使用 MRepo 的最新版本。

### Bug description / Bug 描述

The wlan profile in use has a proxy configured. MRepo does not respect that setting and tries direct connect to internet. which fails.

### Expected behavior / 预期行为

MRepo uses configured proxy.

### Actual behavior / 实际行为

No internet access for MRepo.

### Steps to reproduce / 复现步骤

1. Setup a wlan with proxy with no direct access to the internet
2. Configure this wlan in the phone including the proxy
3. Run MRepo and try to update the repos
4. Error message

### UI / OS

LineageOS

### Android Version / Android 版本

13

**Comment by ya0211** [comment]
MRepo does not handle network configurations, and I am also using a proxy without any issues. Please resolve any proxy-related problems on your own as I do not provide specific support for that.

**Comment by eku** [comment]
> Please resolve any proxy-related problems on your own as I do not provide specific support for that.

I deinstalled MRepo and moved to [MMRL](https://github.com/DerGoogler/MMRL) which uses the configured proxy.
