### ISSUE TITLE
[FR] turn repos on/off and UI suggestion

### ISSUE THREAD

**Issue by G-D-B-9-9** [ya0211/MRepo#87]
### Checklist / 检查清单

- [X] No one has submitted a similar or identical feature request before. / 之前没有人提交过类似或相同的功能请求。
- [X] This suggestion does not depart from the original intention of MRepo. / 这个建议不会背离 MRepo 的初衷。

### Enhancement propose / 改进目的

Good feature would be to turn on and off different repos without removing them.

Also in the repos list module UI box could be more narrow - also utilizing space to the right.

**Comment by ya0211** [comment]
- Support opening/closing of repo 
- About UI suggestions, please give actual design drafts

**Comment by ya0211** [comment]
> Ok now I see ✅ and ❌ but at least in my installation pressing them doesn't update the icon but have to go to another page and then back to see the change of the icon.

This is a bug and I'm not sure why as it is work in debug builds.

**Comment by ya0211** [comment]
Fixed in https://github.com/ya0211/MRepo/commit/b941365fb2bc39854aaeeda776efa7a84460c32e
