### ISSUE TITLE
[BUG] Version 2.2 - Install from Storage: Can't install modules via Mixplorer LAN(Samba)

### ISSUE THREAD

**Issue by Mark-Joy** [ya0211/MRepo#88]
### Checklist / 检查清单

- [X] No one has submitted a similar or identical bug report before. / 之前没有人提交过类似或相同的 bug report。
- [X] I'm using the latest version of MRepo. / 我正在使用 MRepo 的最新版本。

### Bug description / Bug 描述

I have all my apps and modules stored on PC-storage. On my phone. the storage was mapped/mounted using Mixplorer LAN(Samba) feature. On version 2.1, I can use Mixplorer to select and install modules, but I can't do that with version 2.2
```
- Installing 2
'/mnt/appfuse/10563_122/2' does not exist
```

### Expected behavior / 预期行为

Version 2.2 shall works the same as version 2.1 which allows me to install modules through Mixplorer LAN(Samba)

### Actual behavior / 实际行为

Error:
```
- Installing 2
'/mnt/appfuse/10563_122/2' does not exist
```

### Steps to reproduce / 复现步骤

Version 2.1 can install just fine:
https://github.com/ya0211/MRepo/assets/22109528/6e6f0ba3-9b94-4e23-a654-7dfe3ea9a87c

Version 2.2 gives error:
https://github.com/ya0211/MRepo/assets/22109528/9d932674-b47b-4a27-80f0-40b36e734713

### UI / OS

MIUI - xiaomi.eu

### Android Version / Android 版本

9

**Comment by ya0211** [comment]
Can you help me test this version?
- [MRepo-2.2.0.d54ec79-516-release.zip](https://github.com/ya0211/MRepo/files/12867267/MRepo-2.2.0.d54ec79-516-release.zip)

**Comment by Mark-Joy** [comment]
It's working! Thank you!
