### ISSUE TITLE
[FR] Update button for modules as in Magisk

### ISSUE THREAD

**Issue by Mark-Joy** [ya0211/MRepo#89]
### Checklist / 检查清单

- [X] No one has submitted a similar or identical feature request before. / 之前没有人提交过类似或相同的功能请求。
- [X] This suggestion does not depart from the original intention of MRepo. / 这个建议不会背离 MRepo 的初衷。

### Enhancement propose / 改进目的

In magisk, there is an update button if new version of the modules are available.
See [Music ReVanced Extended] and [Play Integrity Fix]
Could not see it in MRepo

![magisk](https://github.com/ya0211/MRepo/assets/22109528/98e70ad3-7f04-4e96-b37c-5340d03e2f50)
![mrepo](https://github.com/ya0211/MRepo/assets/22109528/baa7918e-77a9-4c1f-b804-5a1524a0fd7b)

### Solution / 解决方案

Could you please add this feature?

Thank you.

**Comment by ya0211** [comment]
Not planned

**Comment by Mark-Joy** [comment]
Since MRepo's repo is limited with only around 100 modules, this is really a convenient way of updating modules even when the modules were install from storage.
Without it, I see no difference between using Magisk and MRepo. At least Magisk has the `update` button.
Or perhaps I should use MRepo for installing and Magisk for updating. Well, not perfect but acceptable.

**Comment by ya0211** [comment]
Since MRepo will only check for updates from repositories, it is indeed more convenient to use Magisk if the module implements updateJson.

I would also consider adding a check for updateJson to MRepo.

**Comment by ya0211** [comment]
Added in https://github.com/ya0211/MRepo/commit/0b211fe0d8b363d62229d49e2ea75754580fbcac

**Comment by Mark-Joy** [comment]
Thank you!!
