### ISSUE TITLE
[enhancement] Donate button

### ISSUE THREAD

**Issue by zgfg** [ya0211/MRepo#9]
Could you consider supporting /.github/FUNDING.yml:
_custom: ["https://www.paypal.me/f3ff0"]_

to display Donate button like on the screenshots:

![IMG_20230228_183510](https://user-images.githubusercontent.com/51943147/221932863-b1a3dfd9-aa28-47b4-a854-0fd13cce62d9.jpg)
![Screenshot_2023-02-28-18-20-12-272_com android chrome](https://user-images.githubusercontent.com/51943147/221933030-56abcfc1-a7f9-4eda-992a-0712b6ff6eb4.jpg)

**Comment by ya0211** [comment]
Not support, there is no rule to regulate the provision of donation information.
