### ISSUE TITLE
[FR] Change Language

### ISSUE THREAD

**Issue by pannal** [ya0211/MRepo#92]
### Checklist / 检查清单

- [X] No one has submitted a similar or identical feature request before. / 之前没有人提交过类似或相同的功能请求。
- [X] This suggestion does not depart from the original intention of MRepo. / 这个建议不会背离 MRepo 的初衷。

### Enhancement propose / 改进目的

I'd love to force the app to use the English language instead of my localized one.

**Comment by ya0211** [comment]
- If Android 13+, you can refer to [this](https://developer.android.com/guide/topics/resources/app-languages).
- else, I'm planning.

**Comment by pannal** [comment]
Oh awesome, I always forget about this new system setting. Works, thank you!
