### ISSUE TITLE
[FR]  Add Support For Android 14 

### ISSUE THREAD

**Issue by fgjaee** [ya0211/MRepo#93]
### Checklist / 检查清单

- [X] No one has submitted a similar or identical feature request before. / 之前没有人提交过类似或相同的功能请求。
- [X] This suggestion does not depart from the original intention of MRepo. / 这个建议不会背离 MRepo 的初衷。

### Enhancement propose / 改进目的

Add support for Android 14 

### Solution / 解决方案

Add support for Android 14 

### Additional info / 额外信息

App crashes upon opening on a14. Not sure why. Pixel 6 pro (Raven)

**Comment by ya0211** [comment]
It has been fixed, please download the latest ci version

**Comment by yeedatoy** [comment]
Thanks. Testing now!
